<?php
declare(strict_types=1);

// RemoteJobs SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

RemoteJobsUtility::setRegistrar(function (RemoteJobsUtility $u): void {
    $u->clean = [RemoteJobsClean::class, 'call'];
    $u->done = [RemoteJobsDone::class, 'call'];
    $u->make_error = [RemoteJobsMakeError::class, 'call'];
    $u->feature_add = [RemoteJobsFeatureAdd::class, 'call'];
    $u->feature_hook = [RemoteJobsFeatureHook::class, 'call'];
    $u->feature_init = [RemoteJobsFeatureInit::class, 'call'];
    $u->fetcher = [RemoteJobsFetcher::class, 'call'];
    $u->make_fetch_def = [RemoteJobsMakeFetchDef::class, 'call'];
    $u->make_context = [RemoteJobsMakeContext::class, 'call'];
    $u->make_options = [RemoteJobsMakeOptions::class, 'call'];
    $u->make_request = [RemoteJobsMakeRequest::class, 'call'];
    $u->make_response = [RemoteJobsMakeResponse::class, 'call'];
    $u->make_result = [RemoteJobsMakeResult::class, 'call'];
    $u->make_point = [RemoteJobsMakePoint::class, 'call'];
    $u->make_spec = [RemoteJobsMakeSpec::class, 'call'];
    $u->make_url = [RemoteJobsMakeUrl::class, 'call'];
    $u->param = [RemoteJobsParam::class, 'call'];
    $u->prepare_auth = [RemoteJobsPrepareAuth::class, 'call'];
    $u->prepare_body = [RemoteJobsPrepareBody::class, 'call'];
    $u->prepare_headers = [RemoteJobsPrepareHeaders::class, 'call'];
    $u->prepare_method = [RemoteJobsPrepareMethod::class, 'call'];
    $u->prepare_params = [RemoteJobsPrepareParams::class, 'call'];
    $u->prepare_path = [RemoteJobsPreparePath::class, 'call'];
    $u->prepare_query = [RemoteJobsPrepareQuery::class, 'call'];
    $u->graphql_body = [RemoteJobsGraphql::class, 'body'];
    $u->graphql_errors = [RemoteJobsGraphql::class, 'errors'];
    $u->result_basic = [RemoteJobsResultBasic::class, 'call'];
    $u->result_body = [RemoteJobsResultBody::class, 'call'];
    $u->result_headers = [RemoteJobsResultHeaders::class, 'call'];
    $u->transform_request = [RemoteJobsTransformRequest::class, 'call'];
    $u->transform_response = [RemoteJobsTransformResponse::class, 'call'];
});
